name: PhotoKaz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42988
title: Mike Heller Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0100a6'
    - '#fafafa'
    - '#584827'
    - '#8a7c4d'
    - '#80b658'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
