name: PhotoKaz
favicon: null
layout_spectrum: 0.9395381477661431
typography_spectrum: 0.26300380495376885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06989987404085696
  lightness: 0.0865904288366437
  saturation: 0.06603663065470755
  rhythmicContrast: 0.4949577960651368
purpose: []
